title: Minjung Kim
subtitle: (김형규, @hyungkyukim)
face: /assets/img/hyungkyukim.jpeg
description: Ph.D student in CSE at Chung-ang University
location: Seoul, Korea
email: minjung.kim AT vision.snu.ac.kr
homepage: https://minnjung.github.io
#twitter:
github: https://github.com/kimhyungkyu-1208
linkedin: https://www.linkedin.com/in/rlagudrb1208/
#google_analytics:
theme: jekyll-theme-minimal
#google_scholar:
#semantic_scholar:

plugins:
  - jekyll-seo-tag
